# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/live_chat_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:MySQL123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:3600000}

logging.config=classpath:logback-spring.xml
logging.level.com.visiomatix=${LOG_LEVEL_COM_VISIOMATIX:DEBUG}
logging.level.org.springframework=${LOG_LEVEL_SPRING:DEBUG}
logging.level.org.hibernate.SQL=${LOG_LEVEL_HIBERNATE_SQL:DEBUG}
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=${LOG_LEVEL_HIBERNATE_BINDER:TRACE}

# Flyway
spring.flyway.enabled=${FLYWAY_ENABLED:false}
spring.flyway.locations=classpath:migration
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}

# Chat session expiry/cleanup
chat.session.timeout.duration=${CHAT_SESSION_TIMEOUT:14400000}
chat.session.cleanup.interval=${CHAT_CLEANUP_INTERVAL:3600000}
chat.session.inactive.threshold=${CHAT_INACTIVE_THRESHOLD:900000}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=viral.prajapati.nmims@gmail.com
spring.mail.password=iobl spxy lsdr evmy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

